---
title: "R Markdown Cheatsheet"
output:
  html_document:
    df_print: paged
    theme:
        version: 4
---

```{r include=F}
    knitr::opts_chunk$set(eval=F, error = T, warning = F)
```

# R Markdown

## Header
```{md}
---
title: ""
author: ""
date: ""
output:
  html_document:
    df_print: paged
    theme:
        version: 4
---
```

## Keybinds
***Strg + Alt + I*** insert R Codeblock \
***Alt + -*** insert left Arrow \
***Strg + Shift + M*** insert Pipe \
***Strg + Enter*** Run Current Line \
***Strg + Alt + R*** Run Everything 

## Default Settings
```{md}
'''{r include=F}
    knitr::opts_chunk$set(echo=T, error=T, warning=F)
    options(scipen=999) #Disable Scientific notation in Inline code
'''
```

<span style="color: red">!! IMPORTANT !!</span> `error = T` lets KnitR ignore errors and therefore is able to build regardless. Additionally missing dependencies do not crash the build. 
DO NOT load libraries in the same block as setting the knitr::opts_chunk!

## Settings per block
```{md}
'''{r, label="", include=T, echo=T, eval= T, results="markup", fig.cap=""}
'''
```

- label - name, for debugging
- include - hides code and output in file
- echo - hides code in file
- eval - determines if code is ran
- results - determines the output style
    - markup - standard
    - asis - plain text
    - hidden - not shown
- fig.cap - caption for figure in this block

## Settings

**Tools** &#8594; **Global Options...** &#8594; **Code** &#8594; **Display** to activate ***Rainbow Parenthesis***

## Force Pagebreak

```{md}
    <div style="page-break-after: always;"></div>
```

## Export
<span style="color: red">!! IMPORTANT !!</span> DO NOT KNIT TO PDF!, because a LaTeX installation is required.

- Knit to HTML 
- Click "Open in Browser" in the top right corner
- Then Print the Page to PDF (***Strg + P***)

